### ISSUE TITLE
Multiple Classes

### ISSUE THREAD

**Issue by Anon69420** [dinostheo/sqrap#7]
Hello creator!

I am not sure how I am able to use a specific class when it is defined multiple times. Please see below:
![9f21980a154a03621b6d670339b3c68e](https://user-images.githubusercontent.com/43067376/51389602-bc186a00-1b24-11e9-9c93-f24d03161224.png)

I want to be able to use the third one down, but unsure how.

**Comment by Anon69420** [comment]
As you can see, this is my result.
https://i.gyazo.com/941727afe8b9895f2c06394b169d6154.png

**Comment by dinostheo** [comment]
How the library is now structured you can't get the 3rd `div` with the `class` selector. Also If you try to extract the text from the parent selector you will get whitespaces and tabs as you exactly show in your screenshots.

The only way I can think of getting this value is getting the html of the parent selector.

```
text: [
  {
    selector: '.detailsStatsContainerRight',
    html: true
  }
]
```

Following you can pass its value to a library like [cheerio](https://www.npmjs.com/package/cheerio) to extract the text of every div with that class. Then assuming that the value that you want is always the 3rd in the resulted array, pick that one. 

This approach has many assumptions, but as well as the sqrap library effectiveness will always depend on how well a website is structured.

**Comment by dinostheo** [comment]
I guess this one can close as non issue.
